from setuptools import setup, find_packages

setup(
    name='cogops',
    version='3.0.0',
    author='mnansary',
    author_email='nazmuddoha.ansary.28@gmail.com',
    description='Cognitive Operations for ChatBots — GovOps Agent',
    packages=find_packages(where="."),
    python_requires='>=3.9',
    install_requires=[
        'fastapi>=0.100',
        'uvicorn[standard]>=0.23',
        'streamlit',
        'openai>=2.0',
        'httpx>=0.24',
        'aiohttp>=3.8',
        'redis>=4.5',
        'tenacity>=8.2',
        'pydantic>=2.0',
        'PyYAML',
        'python-dotenv',
        'transformers',
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
